### ISSUE TITLE
the mod...doesnt work?

### ISSUE THREAD

**Issue by TemmieKingYT** [LifeIsAParadox/Skyblocker#1]
I installed it with simple performance mods and things like worldmap and rei , but it doesnt seem to add anything in the game , is it a glitch or something ?

**Comment by LifeIsAParadox** [comment]
strange I have been able to use it for several days.
The mod adds the following:
  * Bars: Health, Mana, Defense, XP.
  * Hide Messages: Ability Cooldown, Heal,
  * AOTE, Implosion, Molten Wave
  * Dungeon Minimap
  * Dungeon Puzzle Solver: Three Weirdos
  * Dwarven Mines Solver: Fetchur, Puzzler
  * Drill Fuel in Item Durability Bar
  * Hotbar Slot Lock Keybind (Select the hotbar slot you want to lock/unlock and press the button)
  * lowest bin price on tools
  
Can you tell me which of these functions does not work?
