### ISSUE TITLE
Bars don't show up on public islands

### ISSUE THREAD

**Issue by Autonomorantula** [LifeIsAParadox/Skyblocker#24]
The bars work just fine on my private island, but when I go to a public island I just see the vanilla stuff.

**Comment by ExternalTime** [comment]
They don't show up at all? Not even with incorrect values?

It's probably a problem with detection of whether you are playing skyblock (which means that none of the features should work).
Can you send a a screenshot of what you see on the sidebar?

**Comment by Autonomorantula** [comment]
Don't know what I did but it works fine now.
