### ISSUE TITLE
new NPC price value display overrides bazaar and lbin price display

### ISSUE THREAD

**Issue by teh404guy** [LifeIsAParadox/Skyblocker#25]
every single item with an NPC buy price shows NPC buy price, only that, no lbin no bazaar
please fix

**Comment by LifeIsAParadox** [comment]
Skyblocker uses moulberry's api for lbin. It looks like moulberry's API is down (https://moulberry.codes/auction_averages_lbin/3day.json). Usually it takes about a day for the problem to be fixed on moulberrys site.
It is planned to use an own api for this but I have little time at the moment.
