### ISSUE TITLE
Master not starting on 1.17.1

### ISSUE THREAD

**Issue by PseudoDistant** [LifeIsAParadox/Skyblocker#47]
I have a few mods as well, may be a mod conflict.

[crash-2022-02-22_21.22.41-client.txt](https://github.com/LifeIsAParadox/Skyblocker/files/8121444/crash-2022-02-22_21.22.41-client.txt)

I could see if I can fix it myself later, but ;-;

**Comment by KonaeAkira** [comment]
at a glance it looks like a mod conflict with appleskin

**Comment by LifeIsAParadox** [comment]
1.5.0 did not really work for 1.17.x. You can either use 1.4.3 for 1.17.x or the latest version for 1.18.x. 
I will try to backport the latest version to 1.17.x. After I successfully backport it, I will pin this issue.

**Comment by LifeIsAParadox** [comment]
We have successfully backport it to 1.17.x
modrinth: https://modrinth.com/mod/skyblocker-liap/version/v1.6.2+1.17.x
github: https://github.com/LifeIsAParadox/Skyblocker/releases/tag/v1.6.2
