### ISSUE TITLE
Off center blaze outline

### ISSUE THREAD

**Issue by ExternalTime** [LifeIsAParadox/Skyblocker#7]
In blaze puzzle the outline for correct blaze is not centered on the blaze.
Besides centering it, it's worth considering to make it closer in size to the actual hitbox.

![2021-09-15_23 26 53](https://user-images.githubusercontent.com/84183548/133517590-2603d1e1-0f02-40eb-8ed7-4339d1bfe9ab.png)

![2021-09-15_23 27 02](https://user-images.githubusercontent.com/84183548/133517616-4de412b3-daa3-4cf3-85d4-12371b69fa83.png)

**Comment by LifeIsAParadox** [comment]
fixed
